### ISSUE TITLE
Fix char handling?

### ISSUE THREAD

**Issue by rudolfkral** [bdfhjk/VIPER#107]
```
int main(void)
{
  int a;
  a = '12';
  return 0;
}
```

Assigns 12 to a.

**Comment by chaser92** [comment]
This should not even parse...?

On Monday, June 8, 2015, Adrian Rudolf Kral notifications@github.com
wrote:

> int main(void)
> {
>   int a;
>   a = '12';
>   return 0;
> }
> 
> Assigns 12 to a.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/issues/107.

## 

Pozdrawiam,
Mariusz Kierski

**Comment by rudolfkral** [comment]
@nutka7
