### ISSUE TITLE
Parser treats enclosing double quotes as part of a string literal

### ISSUE THREAD

**Issue by rudolfkral** [bdfhjk/VIPER#47]
You want "Hello World", you get "\"Hello World\"".

**Comment by chaser92** [comment]
Just a tip; the ` character of Markdown is good for citing code and literals, like this:
You want `Hello World`, you get `"Hello World"`. Please write comments and code review with this if possible. It doesn't take time but adds a lot to readability and viewing pleasure :)

**Comment by chaser92** [comment]
Is this resolved? Please close if so.
