### ISSUE TITLE
The website start with critical javascript error (actual master version)

### ISSUE THREAD

**Issue by bdfhjk** [bdfhjk/VIPER#51]
GET 
http://127.0.0.1:3000/bower_components/lodash/lodash.min.js [HTTP/1.1 404 Not Found 8ms]
Error: Script error for: lodash/lodash.min
http://requirejs.org/docs/errors.html#scripterror require.js:166:16
GET 
http://127.0.0.1:3000/bower_components/sprintf/dist/sprintf.min.js [HTTP/1.1 404 Not Found 2ms]
Error: Script error for: sprintf/sprintf.min
http://requirejs.org/docs/errors.html#scripterror

**Comment by chaser92** [comment]
please run bower install

2015-04-23 13:46 GMT+02:00 bdfhjk notifications@github.com:

> GET
> http://127.0.0.1:3000/bower_components/lodash/lodash.min.js [HTTP/1.1 404
> Not Found 8ms]
> Error: Script error for: lodash/lodash.min
> http://requirejs.org/docs/errors.html#scripterror require.js:166:16
> GET
> http://127.0.0.1:3000/bower_components/sprintf/dist/sprintf.min.js
> [HTTP/1.1 404 Not Found 2ms]
> Error: Script error for: sprintf/sprintf.min
> http://requirejs.org/docs/errors.html#scripterror
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/issues/51.

## 

Pozdrawiam,
Mariusz Kierski

**Comment by bdfhjk** [comment]
Done, working now :+1:  (move this to documentation?)

**Comment by chaser92** [comment]
Yeah there should be a deployment guide, you can prepare one if you know
how or ask me for help

2015-04-23 14:41 GMT+02:00 bdfhjk notifications@github.com:

> Done, working now [image: :+1:](move this to documentation?)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/issues/51#issuecomment-95573168.

## 

Pozdrawiam,
Mariusz Kierski

**Comment by chaser92** [comment]
Maybe let's put a deployment guide in README.md because it has to be on CD
anyway and then copy it to the document

2015-04-23 14:47 GMT+02:00 Mariusz Kierski kartam92@gmail.com:

> Yeah there should be a deployment guide, you can prepare one if you know
> how or ask me for help
> 
> 2015-04-23 14:41 GMT+02:00 bdfhjk notifications@github.com:
> 
> > Done, working now [image: :+1:](move this to documentation?)
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bdfhjk/VIPER/issues/51#issuecomment-95573168.
> 
> ## 
> 
> Pozdrawiam,
> Mariusz Kierski

## 

Pozdrawiam,
Mariusz Kierski
