### ISSUE TITLE
Table variables implementation

### ISSUE THREAD

**Issue by bdfhjk** [bdfhjk/VIPER#54]

**Comment by chaser92** [comment]
There is an error: if I have an array of oversized length, e.g. 10, and I want to mark the 9th element as visited/changed, 0th element is marked instead of the placeholder "..." element.

**Comment by bdfhjk** [comment]
Please check your code one more time and give me an example for this. It's hard to believe, because I seems to don't even touch oversized elements. My test code is changeTable("TestTable", [1,1,1,1,1,1,1,Math.floor((Math.random() \* 6))]); and it's working. Maybe the error is in your testing code (but that's not statement, please help me figure it).

Responsible code is there:

```
function changeTable(tableName, values) {
  var found = false;
  for (i = 0; i < tablesList.length; i++){
    if (tablesList[i].name == tableName){
      for(j = 0; j < tablesList[i].values.length; j++){
        if (tablesList[i].values[j].value != values[j]){
          tablesList[i].values[j].value = values[j];
          tablesList[i].values[j].status = "modified";
        }
      }
      found = true;
    }
  }

  if (!found){
    var t_values = [];
    for(i = 0; i < values.length; i++){
      t_values[i] = {};
      t_values[i].value = values[i];
      t_values[i].status = "modified";
    }
    tablesList.push({name: tableName, values: t_values});
  }
}


  for(j = 0; j < number_to_draw; j++){
    var name = j.toString();
    if (j === 0)
      name = list[i].name;
    variable.draw(svg, 10 + j * cellWidth,
                  start_s * cellHeight + i * cellHeight + 5,
                  name,
                  list[i].values[j].value,
                  list[i].values[j].status);
  }
```

**Comment by chaser92** [comment]
There is no `changeTable` anymore, now it's `changeTableElement`, but the code there was mostly copied. The problem occurs when I actually DO touch an element out of visible range - which I should be able to do.

**Comment by bdfhjk** [comment]
It's still actual?

**Comment by chaser92** [comment]
Yes, it's still unresolved. I'll make a video of what i mean

On Saturday, May 30, 2015, bdfhjk notifications@github.com wrote:

> It's still actual?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/issues/54#issuecomment-107054599.

## 

Pozdrawiam,
Mariusz Kierski
