### ISSUE TITLE
Bower install - put to grunt script or manual

### ISSUE THREAD

**Issue by bdfhjk** [bdfhjk/VIPER#85]
otherwise following dep guide will fail with not found reference. What do you think?

**Comment by chaser92** [comment]
Bower install is already in npm install

On Saturday, May 30, 2015, bdfhjk notifications@github.com wrote:

> Assigned #85 https://github.com/bdfhjk/VIPER/issues/85 to @chaser92
> https://github.com/chaser92.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdfhjk/VIPER/issues/85#event-317912195.

## 

Pozdrawiam,
Mariusz Kierski
